/* A compact, read-only picture dictionary. Canonical meanings and scene bindings
   are supplied by illustration-scenes.json; no etymology data is loaded. */
(() => {
'use strict';
// Developer-only responsive QA, never shown in ordinary navigation. The nested
// document removes the preview flag, so it cannot recursively embed itself.
const previewURL = new URL(location.href);
if (previewURL.searchParams.get('preview') === 'mobile' && window.self === window.top) {
  previewURL.searchParams.delete('preview');
  document.title = '390 × 844 responsive viewport · Picture Dictionary';
  document.body.replaceChildren();
  document.body.style.cssText = 'margin:0;padding:22px 10px;background:#dfe6df;display:flex;flex-direction:column;align-items:center;gap:10px;min-width:410px;';
  const label = document.createElement('p');
  label.textContent = 'Responsive preview · 390 × 844 CSS pixels';
  label.style.cssText = 'font:12px sans-serif;color:#41574a;margin:0;';
  const frame = document.createElement('iframe');
  frame.title = 'Mobile layout preview'; frame.src = previewURL.href;
  frame.style.cssText = 'display:block;width:390px;height:844px;border:0;background:white;box-shadow:0 8px 40px #233b3825;';
  document.body.append(label,frame);
  return;
}
const $ = (s, p=document) => p.querySelector(s);
const $$ = (s, p=document) => [...p.querySelectorAll(s)];
const escapeHTML = text => String(text ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const storage = {get(k){try{return localStorage.getItem(k)}catch{return null}},set(k,v){try{localStorage.setItem(k,v)}catch{}}};
const initialParams = new URLSearchParams(location.search);
let lang = initialParams.get('lang') === 'en' ? 'en' : initialParams.get('lang') === 'ja' ? 'ja' : storage.get('picture-dictionary-language') || 'ja';
let mode='browse', category='all', query=initialParams.get('q')||'', entries=[], filtered=[], current=null, previousFocus=null;
let lookup=new Map(), states=new Map(), toastTimer, renderVersion=0;
const colors=['#e6efdb','#e5edf7','#fff0cf','#f9e4d9','#e0eee8','#f2e9d8'];
const order=['help','under','decision','experience','going','support','attention','food','through','quality','book','water','respect','potential','difficult','knowledge','got','difference','purpose','pressure','seen','taken','says','went','house','car','door','room','floor','fire','arm','eye','heart','feet','felt','ability','understanding','future','loss','between'];
const categoryDefs=[
{id:'all',ja:'すべてのイラスト',en:'All illustrations',icon:'▦',words:[]},
{id:'everyday',ja:'くらしと道具',en:'Everyday life',icon:'⌂',words:['book','door','house','water','food','car','fire','floor','room','felt','quality']},
{id:'people',ja:'人とからだ',en:'People & body',icon:'☺',words:['arm','eye','heart','feet','respect','help','says','attention']},
{id:'ideas',ja:'考えと気づき',en:'Ideas & discovery',icon:'✳',words:['ability','attention','decision','difference','knowledge','potential','purpose','understanding','future']},
{id:'actions',ja:'行動とできごと',en:'Actions & moments',icon:'↗',words:['experience','help','difficult','loss','pressure','support','got','says','seen','taken','respect']},
{id:'places',ja:'位置と移動',en:'Position & movement',icon:'⊙',words:['going','went','between','under','through','car','decision','risk']}
];
// Search vocabulary describes these pictured scenes. It is separate from their
// canonical headwords, meanings, and reviewed illustration descriptions.
const aliases={
help:['手伝う','手伝い','荷物','箱を運ぶ','協力','助け合う','helping','lifting','carrying','box','teamwork'],under:['ねこ','ネコ','猫','いす','椅子','寝る','眠る','位置','cat','sleeping','position'],decision:['考える','選ぶ','迷う','分かれ道','ハイキング','thinking','choice','choose','hiking'],experience:['作る','陶芸','体験','ろくろ','making','pottery'],going:['移動','旅行','出発','別れ','バス','movement','travel','bus'],support:['支える','木','植物','育てる','gardening','plant','tree'],attention:['見る','注目','学ぶ','子供','こども','children','learning','watching'],food:['食べ物','食事','魚','ごはん','みかん','meal','fish','rice'],through:['移動','自転車','トンネル','サイクリング','movement','bicycle','cycling'],quality:['作る','靴','くつ','職人','つくる','shoe','craft','making'],water:['飲み物','注ぐ','コップ','水','drink','pouring'],respect:['お辞儀','おじぎ','尊敬','職人','bow','bowing'],potential:['植物','どんぐり','植える','成長','plant','growing','acorn'],difficult:['登山','登る','山','頑張る','climb','climbing','mountain'],knowledge:['植物','図鑑','葉','調べる','plant','leaf','learning'],got:['プレゼント','自転車','贈り物','gift','bicycle'],difference:['違う','気づく','ボタン','上着','buttons','different'],purpose:['鳥','とり','巣箱','作る','bird','birdhouse'],pressure:['押す','押しつぶす','重い','スポンジ','weight','heavy','sponge'],seen:['鳥','とり','図鑑','野鳥','観察','bird','birdwatching'],taken:['食べる','おやつ','クッキー','eat','eating','cookie'],says:['話す','会話','友達','聞く','talking','speaking','friends'],went:['移動','旅行','お土産','写真','movement','travel','souvenirs'],house:['家','いえ','庭','建物','home','garden'],door:['開く','ドア','扉','open'],room:['部屋','リビング','家具','ソファ','living room','sofa'],floor:['掃除','そうじ','床','モップ','cleaning','mop'],fire:['たき火','焚き火','キャンプ','camping','campfire'],ability:['バイオリン','音楽','演奏','練習','violin','music','practice'],understanding:['パズル','学ぶ','子供','こども','children','learning','puzzle'],future:['計画','未来','模型','橋','plan','bridge'],loss:['穀物','袋','こぼれる','農家','grain','farmer'],between:['積み木','ボール','位置','blocks','ball','position'],car:['移動','車','くるま','道路','movement','road'],feet:['足','あし','からだ','body'],heart:['心臓','しんぞう','からだ','body'],arm:['腕','うで','からだ','body'],eye:['目','め','鏡','からだ','body','mirror'],felt:['布','フェルト','はさみ','工作','fabric','scissors','craft'],risk:['危険','橋','川','壊れる','bridge','river','danger']
};
const words={ja:{brand:'ことばの絵図鑑',edition:'小さなサンプル版',browse:'絵をさがす',smallCollection:'ひとつの絵から、',smallCollection2:'ふたつのことばへ。',sampleNote:'英語と日本語の説明文で、絵に描かれた場面を見てみよう。',gameLink:'ことばのパズルで遊ぶ',eyebrow:'A LITTLE WORLD OF WORDS',title:'どんな<span>場面</span>を探そう？',intro:'気になる絵をひらくと、英語と日本語がつながる。',searchLabel:'単語や場面を検索',placeholder:'単語や場面を検索：箱を運ぶ、help、ねこ…',try:'たとえば',view:'みる',learn:'おぼえる',learningNote:'絵から英単語を思い出してみよう。カードをひらくと答えが見られます。',loading:'絵のページを準備しています…',emptyTitle:'まだ見つからないみたい。',emptyText:'短いことばや、別の言い方で探してみてください。',reset:'すべての絵にもどる',footer:'絵とことばの、小さな辞典。',footerMeta:'日英の説明文 · 透過PNG',background:'背景をチェック',transparent:'背景透過 · 512 × 512',wordLabel:'この絵のことば',sceneLabel:'イラスト解説',revealSentence:'英文を見る',hideSentence:'英文を隠す',download:'透過PNGをダウンロード',downloadNote:'原寸のイラストを保存できます',related:'もう少し、絵で寄り道',previous:'前の絵',next:'次の絵',check:'英単語、わかるかな？',count:n=>`${n} 点`,searchTitle:'検索結果',verifying:'イラストを確認しています…',unavailable:'このイラストの説明文は確認中です。',loadError:'辞典を読み込めませんでした。接続を確認して、もう一度お試しください。',retry:'もう一度読み込む',noSpeech:'このブラウザでは音声を再生できません。',downloadSuccess:'PNGの保存を開始しました',downloadFailed:'保存できませんでした。もう一度お試しください。',openLabel:w=>`${w} のイラストをひらく`,close:'閉じる'},en:{brand:'The Picture Dictionary',edition:'A small sample edition',browse:'EXPLORE',smallCollection:'One little picture.',smallCollection2:'Two ways to say it.',sampleNote:'Explore each illustrated moment in English and Japanese.',gameLink:'Play the word puzzle',eyebrow:'A LITTLE WORLD OF WORDS',title:'Find a word.<br class="en-break"> <span>Picture a moment.</span>',intro:'Little illustrations. Everyday words. A new way to connect them.',searchLabel:'Search words or scenes',placeholder:'Search a word or a scene: carrying a box, cat…',try:'Try',view:'Explore',learn:'Recall',learningNote:'Can you remember the English word? Open a card to see the answer.',loading:'Opening the picture collection…',emptyTitle:'Nothing here just yet.',emptyText:'Try a shorter phrase or another way to describe the scene.',reset:'Back to all illustrations',footer:'A little dictionary of pictures and words.',footerMeta:'English & Japanese · Transparent PNGs',background:'Check background',transparent:'Transparent · 512 × 512',wordLabel:'THE WORD IN THIS PICTURE',sceneLabel:'IN THE ILLUSTRATION',revealSentence:'Show English',hideSentence:'Hide English',download:'Download transparent PNG',downloadNote:'Save the original-size illustration',related:'A few more little discoveries',previous:'Previous',next:'Next',check:'What is the English word?',count:n=>`${n} illustrations`,searchTitle:'Search results',verifying:'Checking the illustration…',unavailable:'This illustration description is being checked.',loadError:'The dictionary could not load. Check your connection and try again.',retry:'Try again',noSpeech:'Speech is unavailable in this browser.',downloadSuccess:'Your PNG download has started',downloadFailed:'The download failed. Please try again.',openLabel:w=>`Open the illustration for ${w}`,close:'Close'}};
const t=k=>words[lang][k];
const normalize=s=>String(s||'').normalize('NFKC').toLowerCase().replace(/[ァ-ヶ]/g,c=>String.fromCharCode(c.charCodeAt(0)-0x60));
const stop=new Set(['a','an','the','is','are','of','in','on','to','and','with','at','by','as','her','his','their','from','を','に','が','は','と','で','の','へ','て','いる','ます','する','こと','ない']);
function tokens(s){s=normalize(s).trim();if(!s)return [];if(/[\u3040-\u9fff]/.test(s)&&Intl.Segmenter){return [...new Intl.Segmenter('ja',{granularity:'word'}).segment(s)].filter(x=>x.isWordLike).map(x=>x.segment).filter(x=>!stop.has(x));}return s.split(/[\s,、。.!?]+/).filter(x=>x&&!stop.has(x));}
function forms(token){const result=[token];if(/ing$/.test(token)&&token.length>5){result.push(token.slice(0,-3),token.slice(0,-3)+'e');if(/(.)\1ing$/.test(token))result.push(token.slice(0,-4));}if(/s$/.test(token)&&token.length>3)result.push(token.slice(0,-1));if(/ed$/.test(token)&&token.length>4)result.push(token.slice(0,-2),token.slice(0,-1));return result;}
function entryCategories(e){return categoryDefs.filter(c=>c.id!=='all'&&c.words.includes(e.w));}
function buildIndex(e){const tags=(e.tags||[]).flatMap(tag=>typeof tag==='string'?[tag]:[tag.en,tag.ja]);return normalize([e.w,e.sense.ja,e.sense.en,e.scene.en,e.scene.ja,...(aliases[e.w]||[]),...tags,...entryCategories(e).flatMap(c=>[c.ja,c.en])].join(' '));}
function score(e,q){if(!q)return 1;const nq=normalize(q).trim(),parts=tokens(nq);if(normalize(e.w)===nq)return 1000;const hay=e._search;if(hay.includes(nq))return 100+(normalize(e.w).startsWith(nq)?100:0);if(!parts.length)return 0;const matches=parts.map(p=>forms(p).some(f=>hay.includes(f)));return matches.every(Boolean)?20+matches.length:0;}
function imageUrl(e){return new URL('../'+e.image.path,location.href).href+'?scene='+encodeURIComponent(e.image.sha256.slice(0,12));}
function syncURL(){const p=new URLSearchParams();if(lang==='en')p.set('lang','en');if(query)p.set('q',query);if(category!=='all')p.set('category',category);const hash=current?'#'+encodeURIComponent(current.w):'';history.replaceState(null,'',location.pathname+(p.size?'?'+p:'')+hash);}
function localize(){document.documentElement.lang=lang;document.title=lang==='ja'?'ことばの絵図鑑 · Etymolingo':'The Picture Dictionary · Etymolingo';$$('[data-i18n]').forEach(el=>{const value=t(el.dataset.i18n);if(typeof value==='string'){if(el.dataset.i18n==='title')el.innerHTML=value;else el.textContent=value;}});$('#searchInput').placeholder=t('placeholder');$('#closeDialog').setAttribute('aria-label',t('close'));$$('[data-lang]').forEach(b=>{b.classList.toggle('selected',b.dataset.lang===lang);b.setAttribute('aria-pressed',String(b.dataset.lang===lang));});$$('[data-query-ja]').forEach(b=>b.textContent=b.dataset[lang==='ja'?'queryJa':'queryEn']);$('#revealSentence').textContent=t('revealSentence');renderCategories();render();}
function renderCategories(){const container=$('#categories');container.replaceChildren();for(const c of categoryDefs){const count=c.id==='all'?entries.length:entries.filter(e=>c.words.includes(e.w)).length;const b=document.createElement('button');b.className='category-button'+(c.id===category?' active':'');b.dataset.category=c.id;b.setAttribute('aria-pressed',String(c.id===category));b.innerHTML=`<span class="category-icon" aria-hidden="true">${c.icon}</span><span>${escapeHTML(c[lang])}</span><span class="count">${count||'—'}</span>`;b.onclick=()=>{category=c.id;renderCategories();render();syncURL();};container.append(b);}}
function render(){const rev=++renderVersion;const selected=categoryDefs.find(c=>c.id===category)||categoryDefs[0];filtered=entries.map(e=>({e,score:score(e,query)})).filter(r=>r.score&&(category==='all'||selected.words.includes(r.e.w))).sort((a,b)=>b.score-a.score||a.e._index-b.e._index).map(r=>r.e);$('#collectionTitle').textContent=query?t('searchTitle'):selected[lang];$('#resultCount').textContent=t('count')(filtered.length);$('#totalCount').textContent=String(entries.length).padStart(2,'0');$('#learningNote').hidden=mode!=='learn';$('#clearSearch').hidden=!query;$('#emptyState').hidden=!!filtered.length;$$('[data-mode]').forEach(b=>{b.classList.toggle('selected',b.dataset.mode===mode);b.setAttribute('aria-pressed',String(b.dataset.mode===mode));});const gallery=$('#results');gallery.replaceChildren();for(const e of filtered){const card=document.createElement('button');card.className='word-card'+(mode==='learn'?' is-hidden':'');card.dataset.word=e.w;card.style.setProperty('--card-bg',e._color);card.setAttribute('aria-label',mode==='learn'?(lang==='ja'?'この絵の英単語を見る':'Reveal the English word'):t('openLabel')(e.w));card.innerHTML=`<span class="card-art"><span class="card-number">${String(e._index+1).padStart(2,'0')}</span><img src="${escapeHTML(imageUrl(e))}" alt="${mode==='learn'?'':escapeHTML(e.sense.ja)}" loading="lazy" width="512" height="512"><span class="card-open" aria-hidden="true">+</span></span><span class="card-info"><span class="word-name" lang="${mode==='learn'?lang:'en'}">${escapeHTML(mode==='learn'?t('check'):e.w)}</span><span class="word-meaning" lang="ja">${escapeHTML(e.sense.ja)}</span></span><span class="card-scene loading" lang="${lang}">&nbsp;</span>`;card.onclick=()=>openDetail(e);const image=card.querySelector('img');image.onerror=()=>{image.style.opacity='.3';card.querySelector('.card-scene').textContent=t('unavailable');card.querySelector('.card-scene').classList.remove('loading');};gallery.append(card);const result=states.get(e.w);if(result)updateCardScene(card,result);else verify(e).then(result=>{if(rev===renderVersion&&card.isConnected)updateCardScene(card,result);});}}
function updateCardScene(card,result){const text=card.querySelector('.card-scene');text.classList.remove('loading');text.textContent=result.status==='reviewed'?result.entry.scene[lang]:t('unavailable');}
const pending=new Map();
async function verify(e){if(states.has(e.w))return states.get(e.w);if(pending.has(e.w))return pending.get(e.w);const promise=(async()=>{let result;try{if(!window.IllustrationScenes)throw Error('Scene helper missing');result=await window.IllustrationScenes.verify(e,{imageUrl:imageUrl(e)});}catch{result={status:'unavailable',entry:e};}states.set(e.w,result);pending.delete(e.w);return result;})();pending.set(e.w,promise);return promise;}
function sentenceHTML(e){const expression=new RegExp('(?<![A-Za-z])('+e.w.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+')(?![A-Za-z])','gi');return escapeHTML(e.scene.en).replace(expression,'<mark>$1</mark>');}
async function openDetail(e,{rememberFocus=true}={}){if(rememberFocus)previousFocus=document.activeElement;current=e;const d=$('#detailDialog');d.style.setProperty('--detail-bg',e._color);$('#detailWord').textContent=e.w;$('#detailMeaning').textContent=e.sense.ja;$('#detailId').textContent='PICTURE '+String(e._index+1).padStart(2,'0');$('#detailImage').src=imageUrl(e);$('#detailImage').alt=e.sense.ja;$('#detailImageWrap').classList.remove('checker');$('#backgroundToggle').setAttribute('aria-pressed','false');$('#sentenceEn').textContent=t('verifying');$('#sentenceEn').classList.remove('masked');$('#sentenceJa').textContent='';$('#revealSentence').hidden=true;$('#downloadImage').disabled=false;$('#downloadNote').textContent=t('downloadNote');$('#detailTags').replaceChildren();const tags=entryCategories(e).map(c=>({label:c[lang],cat:c.id}));for(const tag of tags){const b=document.createElement('button');b.textContent=tag.label;b.onclick=()=>{closeDetail();category=tag.cat;query='';$('#searchInput').value='';renderCategories();render();syncURL();};$('#detailTags').append(b);}const related=entries.filter(x=>x.w!==e.w&&entryCategories(x).some(c=>entryCategories(e).some(y=>y.id===c.id))).slice(0,3);$('#relatedWords').replaceChildren();for(const entry of related){const b=document.createElement('button');b.innerHTML=`<img src="${escapeHTML(imageUrl(entry))}" alt="" width="43" height="43"><span>${escapeHTML(entry.w)}</span>`;b.onclick=()=>openDetail(entry,{rememberFocus:false});$('#relatedWords').append(b);}const pool=filtered.length?filtered:entries;$('#detailPosition').textContent=`${Math.max(0,pool.findIndex(x=>x.w===e.w))+1} / ${pool.length}`;if(!d.open)d.showModal();d.scrollTop=0;document.body.style.overflow='hidden';syncURL();const result=await verify(e);if(!current||current.w!==e.w)return;if(result.status==='reviewed'){$('#sentenceEn').innerHTML=sentenceHTML(e);$('#sentenceJa').textContent=e.scene.ja;$('#revealSentence').hidden=mode!=='learn';$('#sentenceEn').classList.toggle('masked',mode==='learn');$('#revealSentence').textContent=t('revealSentence');$('#detailImage').alt=e.scene[lang];}else{$('#sentenceEn').textContent=t('unavailable');$('#sentenceJa').textContent='';}}
function closeDetail(){if($('#detailDialog').open)$('#detailDialog').close();current=null;document.body.style.overflow='';syncURL();if(previousFocus?.isConnected)previousFocus.focus();}
function advance(direction){if(!current)return;const pool=filtered.length?filtered:entries;let i=pool.findIndex(e=>e.w===current.w);if(i<0)i=0;openDetail(pool[(i+direction+pool.length)%pool.length],{rememberFocus:false});}
function toast(message){clearTimeout(toastTimer);const el=$('#toast');el.textContent=message;el.classList.add('show');toastTimer=setTimeout(()=>el.classList.remove('show'),3200);}
async function download(){if(!current)return;const e=current,b=$('#downloadImage');b.disabled=true;try{const response=await fetch(imageUrl(e));if(!response.ok)throw Error('Download failed');const blob=await response.blob();if(!blob.type.startsWith('image/'))throw Error('Invalid image');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=e.art+'.png';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);toast(t('downloadSuccess'));}catch{toast(t('downloadFailed'));}finally{b.disabled=false;}}
function speak(){if(!('speechSynthesis'in window)){toast(t('noSpeech'));return;}try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(current.w);u.lang='en-US';u.rate=.82;u.onerror=()=>toast(t('noSpeech'));speechSynthesis.speak(u);}catch{toast(t('noSpeech'));}}
$('#searchForm').onsubmit=e=>{e.preventDefault();query=$('#searchInput').value;render();syncURL();};$('#searchInput').value=query;let searchTimer;$('#searchInput').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{query=$('#searchInput').value;render();syncURL();},100);};$('#clearSearch').onclick=()=>{query='';$('#searchInput').value='';render();syncURL();$('#searchInput').focus();};$('#resetSearch').onclick=()=>{category='all';query='';$('#searchInput').value='';renderCategories();render();syncURL();};$$('[data-query-ja]').forEach(b=>b.onclick=()=>{category='all';query=b.dataset[lang==='ja'?'queryJa':'queryEn'];$('#searchInput').value=query;renderCategories();render();syncURL();});$$('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;render();});$$('[data-lang]').forEach(b=>b.onclick=()=>{lang=b.dataset.lang;storage.set('picture-dictionary-language',lang);localize();if(current)openDetail(current,{rememberFocus:false});syncURL();});$('#closeDialog').onclick=closeDetail;$('#detailDialog').addEventListener('cancel',e=>{e.preventDefault();closeDetail();});$('#detailDialog').addEventListener('click',e=>{if(e.target===$('#detailDialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDetail();}});$('#backgroundToggle').onclick=()=>{const active=$('#detailImageWrap').classList.toggle('checker');$('#backgroundToggle').setAttribute('aria-pressed',String(active));};$('#revealSentence').onclick=()=>{const masked=$('#sentenceEn').classList.toggle('masked');$('#revealSentence').textContent=t(masked?'revealSentence':'hideSentence');};$('#downloadImage').onclick=download;$('#speakWord').onclick=speak;$('#previousWord').onclick=()=>advance(-1);$('#nextWord').onclick=()=>advance(1);document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)&&!current){e.preventDefault();$('#searchInput').focus();}if(current&&e.key==='ArrowRight')advance(1);if(current&&e.key==='ArrowLeft')advance(-1);});
window.addEventListener('hashchange',()=>{const w=decodeURIComponent(location.hash.slice(1));if(lookup.has(w)&&current?.w!==w)openDetail(lookup.get(w));else if(!w&&current)closeDetail();});
async function init(){try{const data=await window.IllustrationScenes.load('data/generated-etymon/illustration-scenes.json?v=1');entries=data.entries.filter(e=>(e.status||e.review?.status)==='reviewed'&&e.scene?.en&&e.scene?.ja).sort((a,b)=>(order.indexOf(a.w)<0?999:order.indexOf(a.w))-(order.indexOf(b.w)<0?999:order.indexOf(b.w)));entries.forEach((e,i)=>{e._index=i;e._color=colors[i%colors.length];e._search=buildIndex(e);lookup.set(e.w,e);});if(!entries.length)throw Error('Empty catalog');category=categoryDefs.some(c=>c.id===initialParams.get('category'))?initialParams.get('category'):'all';localize();const w=decodeURIComponent(location.hash.slice(1));if(lookup.has(w))openDetail(lookup.get(w));}catch(error){console.error('Picture dictionary:',error);$('#results').innerHTML=`<div class="load-state"><p>${escapeHTML(t('loadError'))}</p><button class="primary-button" id="retryLoad" style="margin:auto">${escapeHTML(t('retry'))}</button></div>`;$('#retryLoad').onclick=()=>location.reload();$('#emptyState').hidden=true;}}
localize();init();
})();
