import csv,hashlib,json,datetime,shutil
from pathlib import Path
from PIL import Image
import sys
sys.path.insert(0,r'D:\etymon-source\tools');import illustration_scenes as scenes
base=Path(r'D:\etymolingo\work\etymopedia'); n=24; p=base/'codex'/f'prompt_rows_{n:03}.csv'
with p.open(encoding='utf-8-sig',newline='') as f:rd=csv.DictReader(f);fields=rd.fieldnames;rows=list(rd)
with Path(r'D:\etymon-source\tools\word-art-todo.csv').open(encoding='utf-8-sig',newline='') as f:srcmap={r['ファイル名']:r for r in csv.DictReader(f)}
repairs=[('Indo-European.png',r'C:\Users\haiba\.codex\generated_images\01a10a9f-1490-7443-84a9-dfee6c30fde9\exec-488365ab-597d-45be-b27b-8e6c251a0dd7.png','Create a transparent-background 512x512 dictionary illustration for “Indo-European,” referring to the Indo-European language family. Show an adult linguist comparing an unlabeled branching family tree that connects small groups of speakers from Europe and India. Place simple, recognizable silhouettes of the two regions at opposite sides, with thin branches from a shared root linking several speaker groups. Use tiny people and simple speech gestures, but absolutely no writing, letterforms, words, flags, or labels. Keep the family-tree relationship clear and the scene compact. Match the attached invidious.png style only: friendly hand-drawn 2D cartoon, thick rounded dark-brown outlines, simplified rounded forms, warm restrained colors, subtle shading. Fully transparent background, no checkerboard, logo, or watermark.','Indo-European languages branch from a shared root across India and Europe.','インド・ヨーロッパ語族が共通の祖語から分岐し、インドとヨーロッパへ広がっている。','旧画像に禁止された語のラベルがあったため置換。新画像に文字がないことと実画像仕様を確認。'),('Mitra.png',r'C:\Users\haiba\.codex\generated_images\01a10a9f-1490-7443-84a9-dfee6c30fde9\exec-8a7d78ae-30fb-4920-aafd-3c10ae703d3c.png','Create a transparent-background 512x512 dictionary illustration of Mitra, a Hindu god. Depict Mitra as a clearly adult male deity with a calm, kind face, simple royal garments, a modest crown, and a radiant sun disk behind his head. Show him seated on a lotus throne, holding two lotus flowers, with a small offering bowl beside the throne. Keep his body and face masculine and adult; do not portray him as a woman or add invented scripture. Match the attached invidious.png style only: friendly hand-drawn 2D cartoon, thick rounded dark-brown outlines, simplified rounded forms, warm restrained colors, subtle shading. Compact full figure, fully transparent background, no checkerboard, text, symbols, logo, or watermark.','Mitra, a Hindu god, sits on a lotus holding twin pink flowers.','ヒンドゥー教の神ミトラが、蓮華に座って二輪のピンクの花を掲げている。','旧画像が正本の「Hindu god」と性別表現で不一致のため、男性神として修正。新画像を目視確認。')]
for fn,sp,prompt,en_cap,ja_cap,note in repairs:
 tgt=base/'_illust'/f'prompt_rows_{n:03}'/fn; backup=base/'codex'/('_backup_'+fn.replace('.png','')+'_024.png'); shutil.copy2(tgt,backup)
 with Image.open(sp) as im: im=im.convert('RGBA').resize((512,512),Image.Resampling.LANCZOS);assert im.getchannel('A').getextrema()==(0,255);im.save(tgt,'PNG')
 can=srcmap[fn]; row=next(r for r in rows if r['ファイル名']==fn); roots=[x.strip() for x in can['語根'].split('+') if x.strip()]; ja=can['語義']; en=scenes.first_senses({'ja':ja,'en':can['英語']})[1]
 data=tgt.read_bytes(); row.update({'単語':can['単語'],'語根ID_JSON':json.dumps(roots,ensure_ascii=False,separators=(',',':')),'第一英語義':en,'語義SHA256':scenes.sense_digest(can['単語'],roots,ja,en),'実行プロンプト':prompt,'解説英語':en_cap,'解説日本語':ja_cap,'制作状態':'reviewed','要確認理由':'','画像SHA256':hashlib.sha256(data).hexdigest(),'画像GitBlobSHA':hashlib.sha1(b'blob '+str(len(data)).encode()+b'\0'+data).hexdigest(),'検品日時':datetime.datetime.now(datetime.timezone(datetime.timedelta(hours=9))).isoformat(timespec='seconds'),'検品メモ':note+' 512×512 RGBAと実アルファを確認。'})
with p.open('w',encoding='utf-8-sig',newline='') as f:w=csv.DictWriter(f,fieldnames=fields,extrasaction='ignore');w.writeheader();w.writerows(rows)
print('replaced and reviewed Indo-European.png, Mitra.png')
