const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const {validRow,supportsLanguage}=require('./reviewed-scenes.js');
const {output,validateCatalog}=require('./build-dictionary-links.cjs');
const catalog=fs.readFileSync(path.join(__dirname,'catalog.js'),'utf8'),links=fs.readFileSync(path.join(__dirname,'dictionary-links.js'),'utf8');
function scope(order=['catalog','links']){const c={window:{}};for(const name of order)vm.runInNewContext(name==='catalog'?catalog:links,c);return c;}
test('compatibility command validates one common catalog and emits the checked-in view without PNG or data copies',()=>{assert.equal(links,output);const result=validateCatalog();assert.equal(result.rows,scope().window.PICTURE_WORDS_CATALOG.length);assert.ok(result.links>10000);assert.doesNotMatch(links,/base64|dictionaryRequested|dictionarySources|reviewedScene\s*:/);});
test('load order preserves current exact schema2 identities without expanding or mutating discovery',()=>{for(const order of [['catalog','links'],['links','catalog']]){const c=scope(order),before=JSON.stringify(c.window.PICTURE_WORDS_CATALOG),rows=c.window.PICTURE_WORDS_DICTIONARY_LINKS;assert.equal(rows.length,c.window.PICTURE_WORDS_CATALOG.filter(w=>w.bindingStatus==='bound').length);assert.equal(new Set(rows.map(w=>w.id)).size,rows.length);assert.ok(Object.isFrozen(rows));assert.ok(rows.every(validRow));assert.ok(rows.every(w=>c.window.PICTURE_WORDS_CATALOG.includes(w)));assert.equal(JSON.stringify(c.window.PICTURE_WORDS_CATALOG),before);}});
test('mother uses the current canonical image and only its verified current reading',()=>{const c=scope(),w=c.window.PICTURE_WORDS_DICTIONARY_LINKS.find(w=>w.id==='mother'),current=c.window.PICTURE_WORDS_CATALOG.find(w=>w.id==='mother');assert.equal(w,current);assert.equal(w.en,'mother');assert.equal(w.image.path,'assets/word/mother.png');assert.equal(w.w,current.availability.ja.answer);assert.equal(supportsLanguage(w,'ja'),current.availability.ja.playable);});
test('homograph IDs remain distinct, held readings stay disabled, and exact reviewed puzzle overrides survive the compatibility view',()=>{const rows=scope().window.PICTURE_WORDS_DICTIONARY_LINKS;assert(rows.some(w=>w.id==='got@x'));assert(rows.some(w=>w.id==='got@ghend'));const word=rows.find(w=>w.id==='got@x');assert.equal(word.w,'');assert.equal(supportsLanguage(word,'ja'),false);const i=rows.find(w=>w.id==='i');assert.equal(i.w,'わたしは');assert.equal(i.readingEvidence,'reviewed_puzzle_first_reading');assert.equal(supportsLanguage(i,'ja'),true);});
test('old or absent schema1 catalog cannot masquerade as current direct-link rows',()=>{const c={window:{PICTURE_WORDS_CATALOG_META:{schema:1},PICTURE_WORDS_CATALOG:[{id:'old',dictionaryRequested:true}]}};vm.runInNewContext(links,c);assert.equal(c.window.PICTURE_WORDS_DICTIONARY_LINKS.length,0);vm.runInNewContext(catalog,c);assert(c.window.PICTURE_WORDS_DICTIONARY_LINKS.length>0);});
test('missing and held captions remain represented, while language eligibility stays with the common gate',()=>{const rows=scope().window.PICTURE_WORDS_DICTIONARY_LINKS,missing=rows.find(w=>w.description.status==='missing'&&supportsLanguage(w,'en')&&!supportsLanguage(w,'ja')),held=rows.find(w=>w.description.status==='held');assert.ok(missing);assert.equal(missing.description.status,'missing');assert.equal(supportsLanguage(missing,'en'),true);assert.equal(supportsLanguage(missing,'ja'),false);assert.equal(missing.description.en,'');assert.equal(missing.description.ja,'');assert.equal(missing.description.ttsAllowed,false);assert.ok(held);assert.equal(supportsLanguage(held,'en'),false);assert.equal(held.description.ttsAllowed,false);});
test('game resolves exact IDs only from the common catalog and never lazily injects sidecar rows',()=>{const code=fs.readFileSync(path.join(__dirname,'game.js'),'utf8');assert.doesNotMatch(code,/PICTURE_WORDS_DICTIONARY_LINKS|dictionaryRequested|catalog\.push|dictionary-links\.js/);assert.match(code,/supportsLanguage\(entry,button\.dataset\.mode\)/);});
