const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
const H=__dirname;const hash='a5efea344f89bc40812040b6d30170d9db6760a970f57ce7cec0dfbd148a5f6a';
const word={pic:'stimulus',imageRevision:hash};
const game=fs.readFileSync(H+'/game.js','utf8'),offlineSource=fs.readFileSync(H+'/offline.js','utf8');
function stem(source,name){return vm.runInNewContext(source.match(new RegExp('  const '+name+' = (.*);'))[1]);}
test('game and offline URLs share exact immutable identity without changing old words',()=>{const a=stem(game,'imgStem'),b=stem(offlineSource,'artStem');for(const w of [word,{pic:'book'},{pic:'stimulus',imageRevision:'../evil'}])assert.equal(a(w),b(w));assert.equal(a(word),'stimulus@'+hash);assert.equal(a({pic:'book'}),'book');assert.equal(a({pic:'stimulus',imageRevision:'bad'}),'stimulus');});
test('saved old stimulus does not qualify the revised quiz offline',async()=>{const root={isSecureContext:true,caches:{},addEventListener:()=>{}};const nav={onLine:false,serviceWorker:{}};const keys=[{url:'https://example.test/assets/word/stimulus.png'}];vm.runInNewContext(offlineSource,{window:root,navigator:nav,URL,Set,setTimeout,clearTimeout,caches:{open:async()=>({keys:async()=>keys})}});await root.NicolingoOffline.refresh();assert.equal(root.NicolingoOffline.canPlay(word),false);assert.equal(root.NicolingoOffline.canPlay({pic:'stimulus'}),true);keys.push({url:'https://example.test/assets/word/stimulus@'+hash+'.png'});await root.NicolingoOffline.refresh();assert.equal(root.NicolingoOffline.canPlay(word),true);});
test('worker and pack saver use the same existing cache name',()=>{const sw=fs.readFileSync(H+'/../picture-words-sw.js','utf8');assert.equal(sw.match(/const CACHE = '([^']+)'/)[1],offlineSource.match(/const CACHE = '([^']+)'/)[1]);assert.equal(sw.match(/const CACHE = '([^']+)'/)[1],'nicolingo-offline-v2');});
test('previous cache-first SW requests new alias instead of serving old PNG',async()=>{const handlers={};let responsePromise,requested;const oldsw=fs.readFileSync(H+'/../picture-words-sw.js','utf8');const origin='https://example.test';vm.runInNewContext(oldsw,{self:{location:new URL(origin+'/app/games/picture-words-sw.js'),addEventListener:(k,f)=>handlers[k]=f},URL,Request,Response,caches:{open:async()=>({match:async key=>key.url===origin+'/assets/word/stimulus.png'?new Response('OLD'):undefined})},fetch:async req=>{requested=req.url;return new Response('NEW')}});handlers.fetch({request:new Request(origin+'/assets/word/stimulus@'+hash+'.png'),respondWith:p=>responsePromise=p});assert.equal(await (await responsePromise).text(),'NEW');assert.equal(requested,origin+'/assets/word/stimulus@'+hash+'.png');});
test('revision alias is byte-identical to canonical accepted PNG',()=>{const root=path.resolve(H,'../../..');const a=fs.readFileSync(root+'/assets/word/stimulus.png'),b=fs.readFileSync(root+'/assets/word/stimulus@'+hash+'.png');assert.deepEqual(a,b);assert.equal(require('node:crypto').createHash('sha256').update(a).digest('hex'),hash);});
