const {test}=require('node:test');
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const code=fs.readFileSync(__dirname+'/game.js','utf8');
const context={URLSearchParams};
vm.runInNewContext(code.slice(code.indexOf('  function resolveRequestedWord('),code.indexOf('  const requestedWord =')),context);
const resolve=context.resolveRequestedWord;
const scope={window:{}};
vm.runInNewContext(fs.readFileSync(__dirname+'/catalog.js','utf8'),scope);
const source=scope.window.PICTURE_WORDS_CATALOG;
const reviewed=require('./reviewed-scenes.js'),difficulty=require('./difficulty.js');
const pool=difficulty.bilingualCatalog(reviewed.filterCatalog(source));
test('ordinary launch has no requested word and keeps the original pool',()=>{const before=JSON.stringify(pool);assert.equal(resolve('',pool,()=>true).present,false);assert.equal(pool.length,scope.window.PICTURE_WORDS_CATALOG_META.count);assert.equal(JSON.stringify(pool),before);});
test('each eligible stable ID selects exactly that row without changing membership',()=>{const before=JSON.stringify(pool);for(const word of pool){const r=resolve('?word='+encodeURIComponent(word.id),pool,()=>true);assert.equal(r.present,true);assert.equal(pool[r.index].id,word.id);}assert.equal(JSON.stringify(pool),before);});
test('exact composite IDs remain distinct and are not looked up by spelling',()=>{const rows=[{id:'same@one'},{id:'same@two'}];assert.equal(resolve('?word=same%40two',rows,()=>true).index,1);assert.equal(resolve('?word=same',rows,()=>true).index,-1);});
test('unknown, wrong-case and malformed requests never select another puzzle',()=>{for(const q of ['?word=unknown-word','?word=','?word','?word=book&word=boy']){const r=resolve(q,pool,()=>true);assert.equal(r.present,true);assert.equal(r.index,-1);}assert.equal(resolve('?word=BOY',[{id:'boy'}],()=>true).index,-1);});
test('unreviewed or unready rows cannot enter through a dictionary request',()=>{const rejected={...source[0],id:'not-ready',en:'not-ready',updatedArt:false};const eligible=difficulty.bilingualCatalog(reviewed.filterCatalog([...source,rejected]));assert.equal(resolve('?word=not-ready',eligible,()=>true).index,-1);assert.equal(eligible.length,pool.length);assert.doesNotMatch(code,/dictionaryRequested|PICTURE_WORDS_DICTIONARY_LINKS|catalog\.push/);});
test('an eligible word unavailable offline is explicit rather than substituted',()=>{const r=resolve('?word='+encodeURIComponent(pool[0].id),pool,()=>false);assert.equal(r.index,-1);assert.equal(r.reason,'unavailable');});
function boot(request){let selected=[],random=0,shown=0,status=0;const elements={game:{dataset:{}},launchScreen:{open:false,showModal(){this.open=true;shown++;},close(){this.open=false;}}};const c={requestedWord:request,catalog:pool,$:id=>elements[id],loadLevel:i=>selected.push(i),nextUncollected:()=>{random++;return 0;},updateOfflineStatus:()=>status++,mode:'en',index:0,matchMedia:()=>({matches:true}),effectiveLayout:()=> 'desktop',closePlay(){},setFeedback(){}};const start=code.lastIndexOf('  if (requestedWord.present) {');vm.runInNewContext(code.slice(start,code.lastIndexOf('\n})();')),c);return{selected,random,shown,status,elements};}
test('actual requested startup loads only the exact index',()=>{const r=boot({present:true,index:3});assert.deepEqual(r.selected,[3]);assert.equal(r.random,0);});
test('actual unavailable startup is an error and never calls the random selector',()=>{const r=boot({present:true,index:-1});assert.deepEqual(r.selected,[]);assert.equal(r.random,0);assert.equal(r.shown,1);assert.equal(r.elements.game.dataset.state,'error');});
test('ordinary startup still uses the existing discovery selector',()=>{const r=boot({present:false,index:-1});assert.deepEqual(r.selected,[0]);assert.equal(r.random,1);});
test('Play handler cannot bypass an unavailable request',()=>{let handler,played=0;const c={requestedWord:{present:true,index:-1},$:()=>({addEventListener:(_,fn)=>handler=fn}),startPlay:()=>played++};const begin=code.indexOf("  $('startPlay').addEventListener");vm.runInNewContext(code.slice(begin,code.indexOf("  $('closeGame').addEventListener",begin)),c);handler();assert.equal(played,0);c.requestedWord={present:true,index:0};handler();assert.equal(played,1);});
test('offline updates keep invalid requests visibly disabled',()=>{const el={};const c={requestedWord:{present:true,index:-1,reason:'not-eligible'},catalog:pool,offline:{hasSavedScene:()=>false,state:{supported:true,online:true}},supports:()=>true,mode:'en',datasetUnavailable:false,location:{protocol:'https:'},$:id=>el[id]||(el[id]={})};const begin=code.indexOf('  function updateOfflineStatus()');vm.runInNewContext(code.slice(begin,code.indexOf("  $('saveOffline').addEventListener",begin))+';updateOfflineStatus();',c);assert.equal(el.startPlay.hidden,true);assert.equal(el.startPlay.disabled,true);assert.equal(el.saveOffline.hidden,true);assert.equal(el.launchDifficulty.hidden,true);assert.equal(el.reloadReviewedData.hidden,false);assert.match(el.offlineStatus.textContent,/対象ではありません/);});
test('saved record schema and strict validators are not replaced by the request bridge',()=>{assert(code.includes("const KEY = 'word-bloom-v1'"));assert(code.includes('difficulty.bilingualCatalog(window.WordBloomReviewedScenes.filterCatalog(originalCatalog))'));assert.doesNotMatch(code,/localStorage\.removeItem|localStorage\.clear/);});

test('all normal eligible IDs address the exact current dictionary image',()=>{const c={window:{}};vm.runInNewContext(fs.readFileSync(__dirname+'/../../eigo-no-e/data.js','utf8'),c);const dictionary=new Map(c.window.EIGO_NO_E.words.map(w=>[w.id,w]));for(const w of pool){assert.equal(dictionary.get(w.id)?.image.sha256,w.reviewedScene.image.sha256,w.id);}});
