const {test}=require('node:test');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const crypto=require('node:crypto').webcrypto,scenes=require('./reviewed-scenes.js');
const root=path.resolve(__dirname,'../../..'),ctx={window:{}};
vm.runInNewContext(fs.readFileSync(path.join(__dirname,'catalog.js'),'utf8'),ctx);
const catalog=ctx.window.PICTURE_WORDS_CATALOG,meta=ctx.window.PICTURE_WORDS_CATALOG_META;
const word=catalog.find(w=>w.description?.status==='reviewed' && w.availability?.en?.playable),copy=v=>JSON.parse(JSON.stringify(v));
const index=fs.readFileSync(path.join(root,'assets/word/illustration-index.js'));
const png=word && fs.readFileSync(path.join(root,word.image.path));
const manifest=JSON.parse(fs.readFileSync(path.join(root,'app/data/generated-etymon/manifest.json')));
const location={href:'https://example.test/app/games/picture-words.html',protocol:'https:'};
function online({live=manifest,art=png,ix=index,fetcher}={}) {const urls=[];const fetch=fetcher||(async url=>{urls.push(url);return new Response(url.includes('manifest.json')?JSON.stringify(live):url.includes('illustration-index.js')?ix:art,{status:200});});return {runtime:new scenes.Runtime({meta,crypto,location,navigator:{onLine:true},fetcher:fetch,makeImageURL:()=> 'data:image/png;base64,verified'}),urls};}
function missing(status='missing') {const w=copy(word);w.description={status,en:'',ja:'',ttsAllowed:false};delete w.reviewedScene;delete w.sceneAsset;w.w='';w.availability.ja={playable:false,answer:'',reason:'reading_unreviewed'};return w;}
function snapshot(packWord=word,mutate) {const sandbox={window:{}};if(packWord.sceneAsset)vm.runInNewContext(fs.readFileSync(path.join(root,'app/games',packWord.sceneAsset),'utf8'),sandbox);if(mutate)mutate(sandbox.window.PICTURE_WORDS_SCENE_ASSETS[packWord.image.sha256]);return new scenes.Runtime({meta,crypto,location:{href:'file:///repo/app/games/picture-words.html',protocol:'file:'},navigator:{onLine:false},assetRoot:sandbox.window,document:null,fetcher:()=>{throw Error('File mode must not fetch');},makeImageURL:()=> 'data:image/png;base64,verified'});}
test('every generated image row remains in the catalog independently of caption or reading',()=>{assert.ok(word);assert.equal(meta.schema,2);assert.equal(catalog.length,meta.count);assert.equal(scenes.filterCatalog(catalog).length,catalog.length);assert.equal(new Set(catalog.map(w=>w.id)).size,catalog.length);assert.ok(catalog.some(w=>w.description.status==='missing'));assert.ok(catalog.some(w=>!w.availability.ja.playable));});
test('HTTPS checks canonical sources and both actual PNG digests before play',async()=>{const x=online(),r=await x.runtime.prepare(word);assert.equal(r.playable,true);assert.equal(r.status,'reviewed');assert.equal(r.ttsAllowed,true);assert.equal(r.imageVerified,true);assert.equal(r.entry.scene.en,word.description.en);assert.equal(x.urls.length,3);assert.ok(x.urls.every(u=>u.includes('strictScene=1')));assert.ok(Object.isFrozen(r.entry.scene));});
test('missing, stale, and held descriptions remain English-playable without caption text or speech',async()=>{for(const status of ['missing','stale','held']){const w=missing(status);w.updatedArt=false;assert.equal(scenes.validRow(w),true);assert.equal(scenes.supportsLanguage(w,'en'),true);assert.equal(scenes.supportsLanguage(w,'ja'),false);const r=await online().runtime.prepare(w);assert.equal(r.status,status);assert.equal(r.playable,true);assert.equal(r.ttsAllowed,false);assert.equal(r.entry,null);assert.equal(r.imageVerified,true);}});
test('a stale caption hash or stale scenes manifest suppresses speech without removing a verified image',async()=>{const w=copy(word);w.reviewedScene.sense.sha256='0'.repeat(64);const r=await online().runtime.prepare(w);assert.equal(r.status,'stale');assert.equal(r.playable,true);assert.equal(r.ttsAllowed,false);const m=copy(manifest);m.files.illustration_scenes.sha256='0'.repeat(64);const other=await online({live:m}).runtime.prepare(word);assert.equal(other.status,'stale');assert.equal(other.playable,true);});
test('bad headword, roots, caption text or description flag never gains narration',async()=>{for(const mutate of [w=>w.reviewedScene.w='different',w=>w.reviewedScene.p=['different'],w=>w.reviewedScene.scene.en='Fabricated text.',w=>w.description.ttsAllowed=false,w=>w.reviewedScene.scene.ja='']){const w=copy(word);mutate(w);const r=await online().runtime.prepare(w);assert.equal(r.playable,true);assert.equal(r.ttsAllowed,false);assert.equal(r.entry,null);}});
test('stale word manifest, index or image cannot enable a puzzle',async()=>{const m=copy(manifest);m.files.words.sha256='0'.repeat(64);assert.equal((await online({live:m}).runtime.prepare(word)).reason,'stale-catalog');assert.equal((await online({ix:Buffer.from('changed')}).runtime.prepare(word)).reason,'stale-catalog');const wrong=Buffer.from(png);wrong[wrong.length-1]^=1;const r=await online({art:wrong}).runtime.prepare(word);assert.equal(r.reason,'stale-image');assert.equal(r.playable,false);});
test('online failure does not silently replace an image with a local pack',async()=>{assert.equal((await online({fetcher:async()=>{throw Error('network');}}).runtime.prepare(word)).playable,false);});
test('file mode keeps reviewed hash-checked packs and allows local captionless PNG without a reviewed claim',async()=>{const r=await snapshot().prepare(word);assert.equal(r.status,'reviewed');assert.equal(r.imageVerified,true);const w=missing(),other=await snapshot(w).prepare(w);assert.equal(other.status,'missing');assert.equal(other.playable,true);assert.equal(other.imageVerified,false);assert.equal(other.ttsAllowed,false);assert.match(other.imageURL,/^file:/);assert.equal(new URL(other.imageURL).pathname,'/repo/'+w.image.path);});
test('corrupt local packs never fall back to an unchecked original or a caption',async()=>{const runtime=snapshot(word,p=>{const b=Buffer.from(p.base64,'base64');b[b.length-1]^=1;p.base64=b.toString('base64');});assert.equal((await runtime.prepare(word)).reason,'stale-image');});
test('pack validation accepts only exact PNG payloads with no extra script',async()=>{const text=fs.readFileSync(path.join(root,'app/games',word.sceneAsset),'utf8');assert.equal(await scenes.verifyPackScript(word,text,crypto),true);await assert.rejects(()=>scenes.verifyPackScript(word,text+'window.evil=true;',crypto));});
test('duplicate IDs are invalid, but exact homograph IDs and English-only entries do not collapse',()=>{const first=missing(),second=copy(first);second.id+='@second';assert.equal(scenes.filterCatalog([first,second]).length,2);assert.equal(scenes.filterCatalog([first,first]).length,0);for(const reading of ['',null,'漢字','かな/べつ','a', 'あ'.repeat(15)]){const w=copy(first);w.w=reading;w.availability.ja={playable:true,answer:reading};assert.equal(scenes.validRow(w),true);assert.equal(scenes.supportsLanguage(w,'en'),true);assert.equal(scenes.supportsLanguage(w,'ja'),false);}});
test('long, unusual, unresolved and held-image rows stay browsable and cannot substitute a guessed answer',()=>{for(const head of ['antidisestablishmentarianism','ice cream','mother-in-law','<word>','']){const w=missing();w.en=head;w.availability.en={playable:true,answer:head};assert.equal(scenes.validRow(w),true);assert.equal(scenes.supportsLanguage(w,'en'),false);}const w=missing();w.en='I';w.availability.en={playable:true,answer:'I'};assert.equal(scenes.supportsLanguage(w,'en'),true);w.bindingStatus='ownership_pending';assert.equal(scenes.validRow(w),true);assert.equal(scenes.supportsLanguage(w,'en'),false);});
test('canonical paths encode filename punctuation rather than treating it as a query',()=>{const w=missing();w.pic='a?# %';w.image.path='assets/word/'+w.pic+'.png';assert.equal(scenes.validRow(w),true);const url=new URL(online().runtime.canonicalURL(w));assert.equal(decodeURIComponent(url.pathname),'/assets/word/a?# %.png');assert.equal(url.searchParams.get('v'),w.image.sha256);});
