const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const {Pronunciation}=require('./pronunciation.js');
const word={id:'practice',en:'practice',w:'れんしゅう'};
const result={status:'reviewed',entry:{scene:{en:'Violin practice beside a music stand.',ja:'譜面台のそばでのバイオリンの練習。'}}};
function setup(){const calls=[],events=[],timers=new Map();let timer=0,cancelled=0;const synth={getVoices:()=>[{lang:'en-US',localService:true},{lang:'ja-JP',localService:true}],addEventListener(){},speak:u=>calls.push(u),cancel(){cancelled++;}};class Utterance{constructor(text){this.text=text;}};const speech=new Pronunciation({synth,Utterance,onState:e=>events.push(e),setTimer:(fn,ms)=>{timers.set(++timer,{fn,ms});return timer;},clearTimer:id=>timers.delete(id)});return{speech,calls,events,timers,cancelled:()=>cancelled};}
test('correct-answer narration submits exact selected-language description synchronously',()=>{const x=setup();x.speech.speakScene(word,result,'en');assert.equal(x.calls.length,1);assert.equal(x.calls[0].text,result.entry.scene.en);assert.equal(x.calls[0].lang,'en-US');assert.notEqual(x.calls[0].text,word.en);x.speech.speakScene(word,result,'ja');assert.equal(x.calls[1].text,result.entry.scene.ja);assert.equal(x.calls[1].lang,'ja-JP');assert.notEqual(x.calls[1].text,word.w);});
test('normal and slow replay keep the whole description',()=>{const x=setup();x.speech.speakScene(word,result,'ja');x.speech.speakScene(word,result,'ja',true);assert.equal(x.calls[0].text,x.calls[1].text);assert.ok(x.calls[1].rate<x.calls[0].rate);});
test('unreviewed or absent text never falls back to the headword',()=>{for(const bad of [null,{status:'unreviewed',entry:result.entry},{status:'reviewed',entry:{scene:{en:'',ja:''}}}]){const x=setup();assert.equal(x.speech.speakScene(word,bad,'en'),false);assert.equal(x.calls.length,0);assert.equal(x.events.at(-1).state,'unavailable');}});
test('the sound toggle suppresses narration and cancels active audio',()=>{const x=setup();x.speech.speakScene(word,result,'en');x.speech.setEnabled(false);assert.equal(x.cancelled(),1);assert.equal(x.speech.speakScene(word,result,'ja'),false);assert.equal(x.calls.length,1);assert.equal(x.events.at(-1).state,'muted');});
test('Next cancellation invalidates late completion callbacks',()=>{const x=setup();x.speech.speakScene(word,result,'en');const u=x.calls[0];x.speech.stop();const n=x.events.length;u.onstart();u.onend();assert.equal(x.events.length,n);assert.equal(x.timers.size,0);});
test('answer narration remains retryable after browser autoplay refusal',()=>{const x=setup();x.speech.speakScene(word,result,'en');x.calls[0].onerror({error:'not-allowed'});assert.equal(x.events.at(-1).error,'not-allowed');assert.equal(x.speech.speakScene(word,result,'en'),true);assert.equal(x.calls[1].text,result.entry.scene.en);});
test('game does not read or display descriptions before answer, or play a word fallback after it',()=>{const code=fs.readFileSync(__dirname+'/game.js','utf8');const win=code.slice(code.indexOf('  function win()'),code.indexOf('  function animateAcquisition()'));assert.match(win,/speech\.speakScene\(entry, roundScene, mode\)/);assert.doesNotMatch(win,/speech\.speak\(entry/);assert.match(code,/speech\.speak\(entry, mode, false, true\)/);assert.match(code,/sceneRuntime\.prepare\(word\)/);assert.match(code,/roundScene = null; sceneReadingHold = false/);});
